services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - app-network

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-stack
    ports:
      - '3000:3000'
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-stack
    ports:
      - '3001:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
